import * as React from 'react'
export { default as If } from './lib/components/If/If'
export { default as Else } from './lib/components/Else/Else'
export { default as Then } from './lib/components/Then/Then'
export { default as For } from './lib/components/For/For'
export { default as Switch } from './lib/components/Switch/Switch'
